version: 2
jobs:
  build:

    working_directory: ~/quackr

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - run: cd quackr-server && mvn dependency:go-offline

      - run: cd quackr-server && mvn install
