version: 2
jobs:
  build:

    working_directory: ~/quackr

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: quackr-server/quackr-{{ checksum "pom.xml" }}

      - run: cd quackr-server && mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: quackr-server/quackr-{{ checksum "pom.xml" }}

      - run: cd quackr-server && mvn install
